/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ButtonCounter {
    }
}
declare global {
    interface HTMLButtonCounterElement extends Components.ButtonCounter, HTMLStencilElement {
    }
    var HTMLButtonCounterElement: {
        prototype: HTMLButtonCounterElement;
        new (): HTMLButtonCounterElement;
    };
    interface HTMLElementTagNameMap {
        "button-counter": HTMLButtonCounterElement;
    }
}
declare namespace LocalJSX {
    interface ButtonCounter {
    }
    interface IntrinsicElements {
        "button-counter": ButtonCounter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "button-counter": LocalJSX.ButtonCounter & JSXBase.HTMLAttributes<HTMLButtonCounterElement>;
        }
    }
}
